title: Colin Ryan Subido
email: subidocolinryan@gmail.com
logo: /assets/img/icon1.png
description: Always Learning   https://www.linkedin.com/in/colinsubido/   subidocolinryan@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
