title: Colin Ryan Subido
email: subidocolinryan@gmail.com
logo: /assets/img/icon.png
description: Always Learning
url: "https://www.linkedin.com/in/colinsubido/"
#show_downloads: true
theme: jekyll-theme-minimal
