title: Colin Ryan Subido
logo: /assets/img/icon.png
description: Hello, I'm Colin. Self-taught Data Analyst with expertise in data analysis, reporting, and visualization.
#show_downloads: true
theme: jekyll-theme-minimal
