title: Colin Ryan Subido
logo: /assets/img/icon.png
description: Always Learning
email: subidocolinryan@gmail.com
linkedin: https://www.linkedin.com/in/colinsubido/
#show_downloads: true
theme: jekyll-theme-minimal
